Listview class cleanup cleanup
jquery/jquery-mobile pull request #8522
Opened 2016-09-21 10:39 UTC by gabrielschulhof

Remove untracking code from listview and pull new UI that includes auto-untracking.

2016-09-21 16:04 UTC, arschmitz requested changes
How did you do this update i dont see any change to `bower.json`

2016-09-21 16:06 UTC, arschmitz requested changes
Looks like maybe you ran `bowercopy` but didn't update `bower.json` to point to 1.12.1 instead of master

2016-09-27 12:51 UTC, gabrielschulhof commented
@arschmitz I have now updated bower.json to point to 1.12.1 and I have run grunt bowercopy to put the corresponding files into external/jquery-ui.

2016-09-27 13:57 UTC, arschmitz approved these changes

2016-09-27 20:20 UTC, closed without merging